import { Injectable, Logger } from '@nestjs/common';
import type {
  OpenAPIObject,
  ParameterObject,
  ReferenceObject,
} from '@nestjs/swagger';
import type { AiTool } from '../../ai/providers/ai-provider-client.interface';
import { ALLOWED_OPERATIONS } from './allowed-operations';

export interface ResolvedOperation {
  path: string;
  method: string;
  parameters: ParameterObject[];
}

// v1 is read-only — tools are never derived from POST/PUT/PATCH/DELETE, even
// if someone adds its operationId to the allowlist by mistake.
const ALLOWED_HTTP_METHOD = 'get';

@Injectable()
export class ToolRegistryService {
  private readonly logger = new Logger(ToolRegistryService.name);
  private readonly operations = new Map<
    string,
    ResolvedOperation & { summary: string }
  >();

  // Called once from main.ts with the document already generated by
  // SwaggerModule.createDocument() — never regenerates it or fetches it,
  // reuses the same in-memory object from the process.
  loadDocument(document: OpenAPIObject): void {
    this.operations.clear();

    for (const [path, item] of Object.entries(document.paths)) {
      const operation = item[ALLOWED_HTTP_METHOD];
      if (
        !operation?.operationId ||
        !ALLOWED_OPERATIONS.includes(operation.operationId)
      )
        continue;

      this.operations.set(operation.operationId, {
        path,
        method: ALLOWED_HTTP_METHOD,
        parameters: (operation.parameters ?? []).filter(isParameterObject),
        summary:
          operation.summary || operation.description || operation.operationId,
      });
    }

    const missing = ALLOWED_OPERATIONS.filter((id) => !this.operations.has(id));
    if (missing.length) {
      this.logger.warn(
        `Operaciones en el allowlist que no se encontraron en el spec de OpenAPI: ${missing.join(', ')}`,
      );
    }
  }

  getTools(): AiTool[] {
    return Array.from(this.operations.entries()).map(([operationId, op]) => ({
      name: operationId,
      description: op.summary,
      inputSchema: buildInputSchema(op.parameters),
    }));
  }

  getOperation(operationId: string): ResolvedOperation | undefined {
    return this.operations.get(operationId);
  }
}

function isParameterObject(
  param: ParameterObject | ReferenceObject,
): param is ParameterObject {
  return !('$ref' in param);
}

function buildInputSchema(
  parameters: ParameterObject[],
): Record<string, unknown> {
  const properties: Record<string, unknown> = {};
  const required: string[] = [];

  for (const param of parameters) {
    const schemaType =
      param.schema && 'type' in param.schema ? param.schema.type : undefined;
    const schemaFormat =
      param.schema && 'format' in param.schema
        ? param.schema.format
        : undefined;
    properties[param.name] = {
      type: schemaType ?? 'string',
      ...(schemaFormat ? { format: schemaFormat } : {}),
      description: param.description,
    };
    if (param.required) required.push(param.name);
  }

  return {
    type: 'object',
    properties,
    ...(required.length ? { required } : {}),
  };
}
