/** Centralized Nest backend route paths, grouped by domain, so a route rename touches one file. */
export const API_ENDPOINTS = {
  branches: {
    list: (showInactive: boolean) => `/branches${showInactive ? "?showInactive=true" : ""}`,
    base: "/branches",
    byId: (id: string) => `/branches/${id}`,
  },
  businesses: {
    base: "/businesses",
    byId: (id: string) => `/businesses/${id}`,
  },
  ingredients: {
    list: (qs: string) => `/ingredients?${qs}`,
    base: "/ingredients",
    byId: (id: string) => `/ingredients/${id}`,
  },
  products: {
    list: (qs: string) => `/products?${qs}`,
    base: "/products",
    byId: (id: string) => `/products/${id}`,
    variants: (id: string) => `/products/${id}/variants`,
    allVariants: "/products/all-variants",
    posCatalog: (branchId: string) => `/products/pos-catalog?branchId=${branchId}`,
    branchPrices: (productId: string) => `/products/${productId}/branch-prices`,
    duplicate: (id: string) => `/products/${id}/duplicate`,
  },
  promotions: {
    list: (qs: string) => `/promotions${qs}`,
    base: "/promotions",
    byId: (id: string) => `/promotions/${id}`,
    forPos: (branchId: string, date: string) => `/promotions?branchId=${branchId}&date=${date}`,
  },
  variantTypes: {
    list: (qs: string) => `/variant-types${qs}`,
    base: "/variant-types",
    byId: (id: string) => `/variant-types/${id}`,
  },
  users: {
    base: "/users",
    byId: (id: string) => `/users/${id}`,
  },
  stock: {
    list: (qs: string) => `/stock?${qs}`,
    alerts: (branchId?: string) => (branchId ? `/stock/alerts?branchId=${branchId}` : "/stock/alerts"),
    movements: (qs: string) => `/stock/movements?${qs}`,
    purchase: "/stock/purchase",
    adjust: "/stock/adjust",
    productStock: (branchId: string) => `/stock/products?branchId=${branchId}`,
    productMovements: (qs: string) => `/stock/product-movements?${qs}`,
    resaleVariants: "/stock/resale-variants",
    productPurchase: "/stock/product-purchase",
    productAdjust: "/stock/product-adjust",
    byId: (id: string) => `/stock/${id}`,
    productById: (id: string) => `/stock/products/${id}`,
  },
  warehouse: {
    stock: (qs: string) => `/warehouse/stock?${qs}`,
    stockLow: (pageSize = 9999) => `/warehouse/stock?status=low&pageSize=${pageSize}`,
    stockById: (id: string) => `/warehouse/stock/${id}`,
    movements: (qs: string) => `/warehouse/movements?${qs}`,
    productStock: "/warehouse/product-stock",
    productMovements: (qs: string) => `/warehouse/product-movements?${qs}`,
    adjust: "/warehouse/adjust",
    purchase: "/warehouse/purchase",
    transfer: "/warehouse/transfer",
    productPurchase: "/warehouse/product-purchase",
    productAdjust: "/warehouse/product-adjust",
    productTransfer: "/warehouse/product-transfer",
  },
  orders: {
    base: "/orders",
    byBranch: (branchId: string) => `/orders?branchId=${branchId}`,
    kitchen: (branchId: string) => `/orders/kitchen?branchId=${branchId}`,
    ready: (id: string) => `/orders/${id}/ready`,
    cancel: (id: string) => `/orders/${id}/cancel`,
  },
  reports: {
    sales: (qs: string) => `/reports/sales?${qs}`,
    topProducts: (qs: string) => `/reports/top-products?${qs}`,
    daily: (qs: string) => `/reports/daily?${qs}`,
    cashiers: (qs: string) => `/reports/cashiers?${qs}`,
    orders: (qs: string) => `/reports/orders?${qs}`,
  },
  settings: {
    base: "/settings",
    test: "/settings/test",
    raw: "/settings/raw",
    rawByKeys: (keys: string[]) => `/settings/raw?keys=${keys.join(",")}`,
    printer: "/settings/printer",
    kitchenThreshold: "/settings/kitchen-threshold",
  },
  paymentValidation: {
    start: "/payment-validation/start",
    reject: "/payment-validation/reject",
    cancel: "/payment-validation/cancel",
  },
  storage: {
    upload: "/storage/upload",
  },
  devices: {
    base: "/devices",
    byId: (id: string) => `/devices/${id}`,
  },
  employees: {
    list: (qs: string) => `/employees${qs ? `?${qs}` : ""}`,
    base: "/employees",
    byId: (id: string) => `/employees/${id}`,
    credential: (id: string) => `/employees/${id}/credential`,
  },
  attendance: {
    scan: "/attendance/scan",
    history: (qs: string) => `/attendance/history?${qs}`,
  },
  telegram: {
    chats: "/telegram/chats",
    chatById: (id: string) => `/telegram/chats/${id}`,
  },
  public: {
    pizzas: "/public/pizzas",
    branches: "/public/branches",
  },
};
